window.SITE_CONFIG = {
    brand: {
        nameShort: 'Solo So',
        nameFull: 'Solo So Auto',
        logoSrc: 'https://i.ibb.co/NgmZPszW/Cover.png',
        whatsapp: '94775300000',
        phone: '+94 77 530 0000',
        address: 'Colombo-Puttalam Rd, Marawila, Sri Lanka',
        addressShort: 'Marawila, Sri Lanka',
        established: 'Est. 2016',
        location: 'Marawila · Sri Lanka',
        metaTitle: 'Solo So | Sri Lanka\'s Premium Car Dealer',
        metaDescription: 'Sri Lanka\'s finest automotive experience. Lowest down payment, best monthly rates.',
    },
    nav: {
        home: 'Home',
        cars: 'Cars',
        wedding: 'Wedding',
    },
    anniversary: {
        years: '10',
        range: '2016 – 2026',
        label: 'Years in Business',
        tagline: 'දශකයක් සේවයේ',
    },
    preloader: {
        statusLabel: 'Loading',
        states: ['Connecting…', 'Loading Inventory…', 'Fetching Data…', 'Almost Ready…', 'Welcome!'],
    },
    hero: {
        badgeText: 'Sri Lanka\'s Premier Auto Dealer',
        promoBadge: 'Limited Time',
        promoHeadline: 'Drive Home Today',
        promoPrice: 'Best Rates in SL',
        downPaymentText: '🏆 Lowest Down Payment in Sri Lanka',
        monthlyRateText: '🔥 Lowest Monthly Rates Guaranteed',
        ctaWhatsapp: 'WhatsApp Us',
        ctaInventory: 'View Inventory',
        servicesLabel: 'Finance & Leasing',
    },
    finance: {
        heading: 'ශ්‍රී ලංකාවේ ප්‍රමුඛ ණය හා ලීසිං සේවාව. ඔබේ සිහිනයේ රථය අද ම ගෙදර ගන්න.',
        partnersCount: '17+',
        hoverHint: 'We work with 17+ banks and finance companies to get you the best deal possible.',
    },
    stats: {
        sectionLabel: 'Global Reach · ලෝකය පුරා',
        heading1: 'Trusted Across',
        heading2: 'The Globe',
        body: 'ශ්‍රී ලංකාව, ජපානය, දුබායි හා ඕස්ට්‍රේලියාව ඇතුළු රටවල් ගණනාවක් හරහා ප්‍රමාණවත් වාහන.',
        card1Label: 'සතුටු ගනුදෙනුකරුවන්',
        card1Since: 'Since 2016',
        card3Title: 'හොඳම තත්ත්වය සහතික කෙරේ',
        card3Sub: 'Every vehicle passes our rigorous inspection process before it reaches you.',
        countries: [
            { code: 'jp', name: 'Japan' },
            { code: 'ae', name: 'Dubai' },
            { code: 'gb', name: 'UK' },
            { code: 'au', name: 'Australia' },
            { code: 'sg', name: 'Singapore' },
            { code: 'lk', name: 'Sri Lanka' },
            { code: 'de', name: 'Germany' },
            { code: 'us', name: 'USA' },
        ],
    },
    inventory: {
        sectionLabel: 'Fresh Arrivals',
        heading: 'අලුත් රථ',
        fullLabel: 'Full Inventory',
        fullHeading: 'All Vehicles',
        filterAllStatus: 'All',
        filterInStock: 'In Stock',
        filterImportable: 'Importable',
        filterAllCond: 'All',
        filterUnreg: 'Unregistered',
        filterReg: 'Registered',
        noResults: 'No vehicles match your filters',
        flyerTagline: 'Best Rates in Sri Lanka',
        flyerContact: '+94 77 530 0000',
        flyerFooter: 'solosoauto.com · Marawila',
        whatsappCTA: 'විමසන්න / Inquire',
    },
    curator: {
        sideLabel: 'The Team Behind Solo So',
        imageSrc: 'https://i.ibb.co/KjHqS4qr/Heritage.png',
        directorName: 'Solo So Team',
        directorTitle: 'Founder & Director',
        heading1: 'Driven by',
        heading2: 'Passion',
        para1: 'Solo So was founded with one mission — to make premium vehicles accessible to every Sri Lankan family with the most affordable financing options in the country.',
        para2: 'With over 10 years of experience and 500+ happy customers, we have built a reputation for trust, quality, and unbeatable value.',
        quoteText: 'ඔබේ සිහිනයේ රථය ලඟා කර ගැනීමට අපි සිටිමු.',
        quoteAttr: 'Solo So Auto — Marawila, Sri Lanka',
    },
    process: {
        sectionLabel: 'How It Works',
        heading: 'Simple 4-Step Process',
        subtext: 'ඔබේ රථය ලබා ගැනීම ඉතා පහසුයි.',
        steps: [
            { num: 'Step 01', title: 'Browse', body: 'Explore our full inventory online or visit our showroom in Marawila.' },
            { num: 'Step 02', title: 'Import', body: 'We source your ideal vehicle directly from Japan, Dubai, or worldwide auctions.' },
            { num: 'Step 03', title: 'Finance', body: 'Choose from 17+ bank partners with the lowest rates in Sri Lanka.' },
            { num: 'Step 04', title: 'Drive', body: 'Complete paperwork and drive your dream car home — often same day.' },
        ],
    },
    concierge: {
        sectionLabel: 'White-Glove Service',
        heading1: 'We Handle',
        heading2: 'Everything',
        body: 'From selection to delivery, we take care of every detail so you can simply enjoy your new vehicle.',
        services: [
            { title: 'Full Inspection', body: 'Every vehicle undergoes a comprehensive mechanical and aesthetic inspection before delivery.' },
            { title: 'Digital Updates', body: 'Track your import status in real time via WhatsApp updates directly from our team.' },
            { title: 'Fast Delivery', body: 'Once approved, we aim to deliver your vehicle within the shortest possible time.' },
        ],
    },
    legacy: {
        sectionLabel: 'Our Heritage',
        timeline: [
            { year: '2016', title: 'Solo So Founded', body: 'Started operations in Marawila with a small fleet and big ambitions.' },
            { year: '2018', title: 'Japan Import Network', body: 'Established direct connections with Japan\'s top vehicle auction houses.' },
            { year: '2020', title: '200+ Cars Sold', body: 'Milestone reached — 200 satisfied customers across Sri Lanka.' },
            { year: '2022', title: '17+ Finance Partners', body: 'Partnered with leading banks to offer the best financing options nationwide.' },
            { year: '2026', title: '500+ Happy Customers', body: 'A decade of trust, quality, and the lowest down payments in Sri Lanka.' },
        ],
    },
    network: {
        label: 'Our Global Sourcing Network',
    },
    location: {
        sectionLabel: 'Find Us',
        heading: 'Marawila Showroom',
        roadHighlight: 'Colombo–Puttalam Road',
        address: 'Marawila, North Western Province',
        landmarks: [
            '5 min from Marawila town centre',
            'Opposite main bus stop',
            'Easy highway access from Colombo',
        ],
        mapShareLink: 'https://maps.google.com/?q=Marawila,+Sri+Lanka',
        directions: 'Get Directions',
    },
    footer: {
        brandName: 'Solo So Auto',
        tagline: 'Premium Car Dealer · Sri Lanka',
        phone: '+94 77 530 0000',
        location: 'Marawila · Sri Lanka',
        copyright: '© 2026 Solo So Auto. All rights reserved.',
        credit: 'Sri Lanka\'s Finest Automotive Experience',
        bottomBar: 'Colombo–Puttalam Rd, Marawila · +94 77 530 0000 · solosoauto.com',
    },
    wedding: {
        sectionLabel: 'Wedding Fleet',
        heading1: 'Your Perfect',
        heading2: 'Wedding Ride',
        body: 'ඔබේ විවාහ දිනය අමතක නොවන ලෙස සාදා ගැනීමට Solo So Wedding Fleet.',
        bookCTA: 'Book Now',
    },
};
